<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Aero\src\Aero.Core\Aero.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Markdig" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="HtmlElementManifest.json" />
  </ItemGroup>

</Project>
