<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <PackageId>Aero.Cms.UI</PackageId>
    <Description>Reusable Aero CMS root Razor components and server-side static assets.</Description>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aero.Cms.Client\Aero.Cms.Client.csproj" />
    <ProjectReference Include="..\Aero.Cms.Contracts\Aero.Cms.Contracts.csproj" />
    <ProjectReference Include="..\Aero.Cms.Shared\Aero.Cms.Shared.csproj" />
  </ItemGroup>

</Project>
