using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aero.Cms.SourceGenerators;

/// <summary>
/// Incremental source generator that discovers <c>[ContentType]</c>-decorated classes
/// at compile time and emits:
/// <list type="bullet">
///   <item>
///     <c>GeneratedContentTypes</c> — a static manifest class with
///     <c>ContentTypeDefinition</c> instances for all discovered content types.
///   </item>
///   <item>
///     <c>GeneratedContentJsonContext</c> — a <c>[JsonSerializable]</c> partial
///     <c>JsonSerializerContext</c> for content type infrastructure types and
///     discovered content type models (emitted only when the infrastructure types
///     exist in the compilation).
///   </item>
/// </list>
/// </summary>
/// <remarks>
/// The generator also injects public <c>ContentTypeAttribute</c> and
/// <c>ContentFieldAttribute</c> definitions into each consuming compilation. Content-field
/// annotations are not currently projected into the generated manifest; emitted definitions have
/// empty field collections.
/// </remarks>
[Generator]
public sealed class ContentTypeGenerator : IIncrementalGenerator
{
    private const string ContentTypeAttributeMetadataName = "Aero.Cms.Abstractions.ContentTypeAttribute";
    private const string ContentFieldAttributeMetadataName = "Aero.Cms.Abstractions.ContentFieldAttribute";

    private const string ContentTypeDefinitionTypeName = "Aero.Cms.Abstractions.ContentTypeDefinition";
    private const string ContentItemTypeName = "Aero.Cms.Abstractions.ContentItem";
    private const string ContentFieldDefinitionTypeName = "Aero.Cms.Abstractions.ContentFieldDefinition";

    private static readonly DiagnosticDescriptor DuplicateContentTypeAlias = new(
        "AERO020",
        "Duplicate CMS content type alias",
        "Content type alias '{0}' is declared by more than one class",
        "AeroCMS.ContentTypes",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>
    /// Registers attribute injection, local manifest discovery, and cross-assembly JSON-context discovery.
    /// </summary>
    /// <param name="context">The incremental generator registration context.</param>
    /// <remarks>
    /// AERO020 is reported as an error for case-insensitive duplicate aliases in the current
    /// project's source. The manifest is still emitted after the diagnostic. Cross-assembly
    /// discovery walks namespace-level types in the current compilation and all references; nested
    /// types are not traversed.
    /// </remarks>
public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit marker attributes so they exist at compile time in any project
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("ContentTypeAttribute.g.cs", SourceText.From("""
                // <auto-generated />
                #pragma warning disable CS1591
                using System;

                namespace Aero.Cms.Abstractions;

                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public sealed class ContentTypeAttribute : Attribute
                {
                    public string Alias { get; }
                    public string Name { get; }
                    public ContentTypeAttribute(string alias, string name)
                    {
                        Alias = alias;
                        Name = name;
                    }
                }
                """, Encoding.UTF8));

            ctx.AddSource("ContentFieldAttribute.g.cs", SourceText.From("""
                // <auto-generated />
                #pragma warning disable CS1591
                using System;

                namespace Aero.Cms.Abstractions;

                [AttributeUsage(AttributeTargets.Property, Inherited = false)]
                public sealed class ContentFieldAttribute : Attribute
                {
                    public string FieldType { get; set; } = "text";
                    public bool Required { get; set; }
                }
                """, Encoding.UTF8));
        });

        // Pipeline 1: Local source discovery — finds [ContentType] in current project's source
        var localContentTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            ContentTypeAttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => GetContentTypeCandidate(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!.Value)
            .Collect();

        // Pipeline 2: Cross-assembly discovery — finds content types from referenced assemblies
        // and checks whether content type infrastructure types exist in the compilation
        var crossAssemblyContentTypes = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var ctAttr = compilation.GetTypeByMetadataName(ContentTypeAttributeMetadataName);
                if (ctAttr is null)
                    return new CrossAssemblyResult(ImmutableArray<DiscoveredContentType>.Empty, false);

                var hasInfrastructureTypes =
                    compilation.GetTypeByMetadataName(ContentTypeDefinitionTypeName) is not null;

                var results = new List<DiscoveredContentType>();

                foreach (var module in compilation.Assembly.Modules)
                    CollectContentTypes(module.GlobalNamespace, ctAttr, results);

                foreach (var reference in compilation.References)
                {
                    if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol asm)
                        CollectContentTypes(asm.GlobalNamespace, ctAttr, results);
                }

                return new CrossAssemblyResult(results.ToImmutableArray(), hasInfrastructureTypes);
            });

        // Output 1: GeneratedContentTypes manifest (for dev-time ContentTypeDefinition)
        context.RegisterSourceOutput(localContentTypes, static (spc, types) =>
        {
            if (types.IsDefaultOrEmpty)
                return;

            ReportDuplicateAliases(spc, types);

            spc.AddSource("GeneratedContentTypes.g.cs",
                SourceText.From(RenderContentTypesManifest(types), Encoding.UTF8));
        });

        // Output 2: Generated content JSON context (for the shim project)
        context.RegisterSourceOutput(crossAssemblyContentTypes, static (spc, result) =>
        {
            // Skip if no types discovered and infrastructure types aren't available
            if (result.Types.IsDefaultOrEmpty && !result.HasInfrastructureTypes)
                return;

            spc.AddSource("GeneratedContentJsonContext.g.cs",
                SourceText.From(RenderContentJsonContext(result.Types, result.HasInfrastructureTypes), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Reports AERO020 for each case-insensitive alias group containing multiple local candidates.
    /// </summary>
    /// <param name="spc">The source-production context used to report diagnostics.</param>
    /// <param name="types">The current project's attributed content types.</param>
    private static void ReportDuplicateAliases(SourceProductionContext spc, ImmutableArray<ContentTypeCandidate> types)
    {
        foreach (var group in types
            .GroupBy(static t => t.Alias, StringComparer.OrdinalIgnoreCase)
            .Where(static g => g.Count() > 1))
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                DuplicateContentTypeAlias, Location.None, group.Key));
        }
    }

    /// <summary>
    /// Reads constructor metadata from an attributed local content-type class.
    /// </summary>
    /// <param name="ctx">The attribute syntax context.</param>
    /// <returns>The candidate metadata, or <see langword="null"/> when the target or attribute is unusable.</returns>
    private static ContentTypeCandidate? GetContentTypeCandidate(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
            return null;

        var attr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.Name == "ContentTypeAttribute");
        if (attr is null || attr.ConstructorArguments.Length < 1)
            return null;

        return new ContentTypeCandidate(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            (string)attr.ConstructorArguments[0].Value!,
            attr.ConstructorArguments.Length > 1 ? (string)attr.ConstructorArguments[1].Value! : "",
            type.Locations.FirstOrDefault());
    }

    /// <summary>
    /// Recursively scans namespace members for types decorated with the resolved content-type attribute.
    /// </summary>
    /// <param name="ns">The namespace whose direct types and child namespaces are inspected.</param>
    /// <param name="ctAttr">The compilation-specific attribute symbol used for identity comparison.</param>
    /// <param name="results">The destination list to append to.</param>
    /// <remarks>Nested types declared inside other types are not inspected.</remarks>
    private static void CollectContentTypes(
        INamespaceSymbol ns,
        INamedTypeSymbol ctAttr,
        List<DiscoveredContentType> results)
    {
        foreach (var member in ns.GetTypeMembers())
        {
            var attr = member.GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, ctAttr));
            if (attr is null)
                continue;

            var alias = attr.ConstructorArguments.Length > 0
                ? (string)attr.ConstructorArguments[0].Value!
                : "";
            var name = attr.ConstructorArguments.Length > 1
                ? (string)attr.ConstructorArguments[1].Value!
                : "";

            results.Add(new DiscoveredContentType(
                member.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                alias,
                name));
        }

        foreach (var nested in ns.GetNamespaceMembers())
            CollectContentTypes(nested, ctAttr, results);
    }

    /// <summary>
    /// Renders local content-type definitions and a case-insensitive alias dictionary.
    /// </summary>
    /// <param name="types">The local candidates in incremental pipeline order.</param>
    /// <returns>C# source for <c>GeneratedContentTypes.g.cs</c>.</returns>
    /// <remarks>
    /// Each definition includes only alias and name; its field collection is empty. Generated
    /// property names derive from the display name and may collide even when aliases are distinct.
    /// </remarks>
    private static string RenderContentTypesManifest(ImmutableArray<ContentTypeCandidate> types)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Aero.Cms.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated content type definitions from [ContentType] attributes.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class GeneratedContentTypes");
        sb.AppendLine("{");

        foreach (var type in types)
        {
            var fieldName = SanitizeIdentifier(type.Name) + "Type";
            sb.AppendLine($"    public static ContentTypeDefinition {fieldName} {{ get; }} = new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        Alias = \"{Escape(type.Alias)}\",");
            sb.AppendLine($"        Name = \"{Escape(type.Name)}\",");
            sb.AppendLine($"        Fields = {{ }}");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        sb.AppendLine("    public static IReadOnlyDictionary<string, ContentTypeDefinition> All { get; }");
        sb.AppendLine("        = new Dictionary<string, ContentTypeDefinition>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");
        foreach (var type in types)
        {
            var fieldName = SanitizeIdentifier(type.Name) + "Type";
            sb.AppendLine($"            [\"{Escape(type.Alias)}\"] = {fieldName},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("}");
        sb.AppendLine("#pragma warning restore CS1591");
        return sb.ToString();
    }

    /// <summary>
    /// Renders the source-generated JSON serializer context.
    /// </summary>
    /// <param name="types">Content types discovered across the compilation and references.</param>
    /// <param name="hasInfrastructureTypes">
    /// Whether <c>ContentTypeDefinition</c> was resolved; this flag gates all serializer registrations.
    /// </param>
    /// <returns>C# source for <c>GeneratedContentJsonContext.g.cs</c>.</returns>
    /// <remarks>
    /// The infrastructure check tests only <c>ContentTypeDefinition</c>, although emitted registrations
    /// also reference <c>ContentItem</c> and <c>ContentFieldDefinition</c>.
    /// </remarks>
    private static string RenderContentJsonContext(
        ImmutableArray<DiscoveredContentType> types,
        bool hasInfrastructureTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Aero.Cms.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated JSON serializer context for content type models.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[JsonSourceGenerationOptions(");
        sb.AppendLine("    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,");
        sb.AppendLine("    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("    GenerationMode = JsonSourceGenerationMode.Default | JsonSourceGenerationMode.Metadata)]");

        if (hasInfrastructureTypes)
        {
            // Emit content type infrastructure type registrations only when the
            // actual types exist in the compilation. This avoids compile errors
            // in projects that don't yet reference Aero.Cms.Abstractions.
            sb.AppendLine("[JsonSerializable(typeof(ContentItem))]");
            sb.AppendLine("[JsonSerializable(typeof(ContentTypeDefinition))]");
            sb.AppendLine("[JsonSerializable(typeof(ContentFieldDefinition))]");
            sb.AppendLine("[JsonSerializable(typeof(List<ContentFieldDefinition>))]");
            sb.AppendLine("[JsonSerializable(typeof(Dictionary<string, JsonElement>))]");
            sb.AppendLine("[JsonSerializable(typeof(JsonElement))]");

            // Register each content type's fully-qualified type
            foreach (var type in types)
            {
                sb.AppendLine($"[JsonSerializable(typeof({type.FullyQualifiedName}))]");
            }
        }

        sb.AppendLine();
        sb.AppendLine("public partial class GeneratedContentJsonContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");
        sb.AppendLine("#pragma warning restore CS1591");

        return sb.ToString();
    }

    /// <summary>
    /// Converts a content type name to an alphanumeric/underscore property-name prefix.
    /// </summary>
    /// <param name="value">The display name to sanitize.</param>
    /// <returns>The sanitized identifier, or <c>Generated</c> for an empty value.</returns>
    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        return sb.Length == 0 ? "Generated" : sb.ToString();
    }

    /// <summary>
    /// Escapes backslashes and quotation marks for a generated C# string literal.
    /// </summary>
    /// <param name="value">The attribute value to escape.</param>
    /// <returns>The escaped literal content, without surrounding quotation marks.</returns>
    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>
    /// Captures an attributed content type declared in the current project's source.
    /// </summary>
    private readonly struct ContentTypeCandidate
    {
        /// <summary>
        /// Gets the fully qualified model type name.
        /// </summary>
public readonly string FullyQualifiedName;
        /// <summary>
        /// Gets the declared content-type alias.
        /// </summary>
public readonly string Alias;
        /// <summary>
        /// Gets the declared display name.
        /// </summary>
public readonly string Name;
        /// <summary>
        /// Gets the model's first source location, when available.
        /// </summary>
public readonly Location? Location;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentTypeCandidate"/> class.
        /// </summary>
        /// <param name="fqn">The fully qualified model type name.</param>
        /// <param name="alias">The declared content-type alias.</param>
        /// <param name="name">The declared display name.</param>
        /// <param name="location">The model's first source location.</param>
public ContentTypeCandidate(string fqn, string alias, string name, Location? location)
        {
            FullyQualifiedName = fqn;
            Alias = alias;
            Name = name;
            Location = location;
        }
    }

    /// <summary>
    /// Captures a namespace-level content type discovered for JSON registration.
    /// </summary>
    private readonly struct DiscoveredContentType
    {
        /// <summary>
        /// Gets the fully qualified model type name.
        /// </summary>
public readonly string FullyQualifiedName;
        /// <summary>
        /// Gets the declared alias retained with discovery metadata.
        /// </summary>
public readonly string Alias;
        /// <summary>
        /// Gets the declared display name retained with discovery metadata.
        /// </summary>
public readonly string Name;

        /// <summary>
        /// Initializes a new instance of the <see cref="DiscoveredContentType"/> class.
        /// </summary>
        /// <param name="fqn">The fully qualified model type name.</param>
        /// <param name="alias">The declared content-type alias.</param>
        /// <param name="name">The declared display name.</param>
public DiscoveredContentType(string fqn, string alias, string name)
        {
            FullyQualifiedName = fqn;
            Alias = alias;
            Name = name;
        }
    }

    /// <summary>
    /// Carries cross-assembly discovery output and the infrastructure availability flag.
    /// </summary>
    private readonly struct CrossAssemblyResult
    {
        /// <summary>
        /// Gets the discovered namespace-level content types.
        /// </summary>
public readonly ImmutableArray<DiscoveredContentType> Types;
        /// <summary>
        /// Gets whether <c>ContentTypeDefinition</c> exists in the compilation.
        /// </summary>
public readonly bool HasInfrastructureTypes;

        /// <summary>
        /// Initializes a new instance of the <see cref="CrossAssemblyResult"/> class.
        /// </summary>
        /// <param name="types">The discovered content types.</param>
        /// <param name="hasInfrastructureTypes">Whether <c>ContentTypeDefinition</c> was resolved.</param>
public CrossAssemblyResult(
            ImmutableArray<DiscoveredContentType> types,
            bool hasInfrastructureTypes)
        {
            Types = types;
            HasInfrastructureTypes = hasInfrastructureTypes;
        }
    }
}
