using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aero.Cms.SourceGenerators;

/// <summary>
/// Incremental source generator that discovers <c>[ContentType]</c>-decorated classes
/// at compile time and emits:
/// <list type="bullet">
///   <item>
///     <c>GeneratedContentTypes</c> — a static manifest class with
///     <c>ContentTypeDefinition</c> instances for all discovered content types.
///   </item>
///   <item>
///     <c>GeneratedContentJsonContext</c> — a <c>[JsonSerializable]</c> partial
///     <c>JsonSerializerContext</c> for content type infrastructure types and
///     discovered content type models (emitted only when the infrastructure types
///     exist in the compilation).
///   </item>
/// </list>
/// </summary>
[Generator]
public sealed class ContentTypeGenerator : IIncrementalGenerator
{
    private const string ContentTypeAttributeMetadataName = "Aero.Cms.Abstractions.ContentTypeAttribute";
    private const string ContentFieldAttributeMetadataName = "Aero.Cms.Abstractions.ContentFieldAttribute";

    private const string ContentTypeDefinitionTypeName = "Aero.Cms.Abstractions.ContentTypeDefinition";
    private const string ContentItemTypeName = "Aero.Cms.Abstractions.ContentItem";
    private const string ContentFieldDefinitionTypeName = "Aero.Cms.Abstractions.ContentFieldDefinition";

    private static readonly DiagnosticDescriptor DuplicateContentTypeAlias = new(
        "AERO020",
        "Duplicate CMS content type alias",
        "Content type alias '{0}' is declared by more than one class",
        "AeroCMS.ContentTypes",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit marker attributes so they exist at compile time in any project
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("ContentTypeAttribute.g.cs", SourceText.From("""
                // <auto-generated />
                using System;

                namespace Aero.Cms.Abstractions;

                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public sealed class ContentTypeAttribute : Attribute
                {
                    public string Alias { get; }
                    public string Name { get; }
                    public ContentTypeAttribute(string alias, string name)
                    {
                        Alias = alias;
                        Name = name;
                    }
                }
                """, Encoding.UTF8));

            ctx.AddSource("ContentFieldAttribute.g.cs", SourceText.From("""
                // <auto-generated />
                using System;

                namespace Aero.Cms.Abstractions;

                [AttributeUsage(AttributeTargets.Property, Inherited = false)]
                public sealed class ContentFieldAttribute : Attribute
                {
                    public string FieldType { get; set; } = "text";
                    public bool Required { get; set; }
                }
                """, Encoding.UTF8));
        });

        // Pipeline 1: Local source discovery — finds [ContentType] in current project's source
        var localContentTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            ContentTypeAttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => GetContentTypeCandidate(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!.Value)
            .Collect();

        // Pipeline 2: Cross-assembly discovery — finds content types from referenced assemblies
        // and checks whether content type infrastructure types exist in the compilation
        var crossAssemblyContentTypes = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var ctAttr = compilation.GetTypeByMetadataName(ContentTypeAttributeMetadataName);
                if (ctAttr is null)
                    return new CrossAssemblyResult(ImmutableArray<DiscoveredContentType>.Empty, false);

                var hasInfrastructureTypes =
                    compilation.GetTypeByMetadataName(ContentTypeDefinitionTypeName) is not null;

                var results = new List<DiscoveredContentType>();

                foreach (var module in compilation.Assembly.Modules)
                    CollectContentTypes(module.GlobalNamespace, ctAttr, results);

                foreach (var reference in compilation.References)
                {
                    if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol asm)
                        CollectContentTypes(asm.GlobalNamespace, ctAttr, results);
                }

                return new CrossAssemblyResult(results.ToImmutableArray(), hasInfrastructureTypes);
            });

        // Output 1: GeneratedContentTypes manifest (for dev-time ContentTypeDefinition)
        context.RegisterSourceOutput(localContentTypes, static (spc, types) =>
        {
            if (types.IsDefaultOrEmpty)
                return;

            ReportDuplicateAliases(spc, types);

            spc.AddSource("GeneratedContentTypes.g.cs",
                SourceText.From(RenderContentTypesManifest(types), Encoding.UTF8));
        });

        // Output 2: Generated content JSON context (for the shim project)
        context.RegisterSourceOutput(crossAssemblyContentTypes, static (spc, result) =>
        {
            // Skip if no types discovered and infrastructure types aren't available
            if (result.Types.IsDefaultOrEmpty && !result.HasInfrastructureTypes)
                return;

            spc.AddSource("GeneratedContentJsonContext.g.cs",
                SourceText.From(RenderContentJsonContext(result.Types, result.HasInfrastructureTypes), Encoding.UTF8));
        });
    }

    private static void ReportDuplicateAliases(SourceProductionContext spc, ImmutableArray<ContentTypeCandidate> types)
    {
        foreach (var group in types
            .GroupBy(static t => t.Alias, StringComparer.OrdinalIgnoreCase)
            .Where(static g => g.Count() > 1))
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                DuplicateContentTypeAlias, Location.None, group.Key));
        }
    }

    private static ContentTypeCandidate? GetContentTypeCandidate(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
            return null;

        var attr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.Name == "ContentTypeAttribute");
        if (attr is null || attr.ConstructorArguments.Length < 1)
            return null;

        return new ContentTypeCandidate(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            (string)attr.ConstructorArguments[0].Value!,
            attr.ConstructorArguments.Length > 1 ? (string)attr.ConstructorArguments[1].Value! : "",
            type.Locations.FirstOrDefault());
    }

    private static void CollectContentTypes(
        INamespaceSymbol ns,
        INamedTypeSymbol ctAttr,
        List<DiscoveredContentType> results)
    {
        foreach (var member in ns.GetTypeMembers())
        {
            var attr = member.GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, ctAttr));
            if (attr is null)
                continue;

            var alias = attr.ConstructorArguments.Length > 0
                ? (string)attr.ConstructorArguments[0].Value!
                : "";
            var name = attr.ConstructorArguments.Length > 1
                ? (string)attr.ConstructorArguments[1].Value!
                : "";

            results.Add(new DiscoveredContentType(
                member.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                alias,
                name));
        }

        foreach (var nested in ns.GetNamespaceMembers())
            CollectContentTypes(nested, ctAttr, results);
    }

    private static string RenderContentTypesManifest(ImmutableArray<ContentTypeCandidate> types)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Aero.Cms.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated content type definitions from [ContentType] attributes.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class GeneratedContentTypes");
        sb.AppendLine("{");

        foreach (var type in types)
        {
            var fieldName = SanitizeIdentifier(type.Name) + "Type";
            sb.AppendLine($"    public static ContentTypeDefinition {fieldName} {{ get; }} = new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        Alias = \"{Escape(type.Alias)}\",");
            sb.AppendLine($"        Name = \"{Escape(type.Name)}\",");
            sb.AppendLine($"        Fields = {{ }}");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        sb.AppendLine("    public static IReadOnlyDictionary<string, ContentTypeDefinition> All { get; }");
        sb.AppendLine("        = new Dictionary<string, ContentTypeDefinition>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");
        foreach (var type in types)
        {
            var fieldName = SanitizeIdentifier(type.Name) + "Type";
            sb.AppendLine($"            [\"{Escape(type.Alias)}\"] = {fieldName},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RenderContentJsonContext(
        ImmutableArray<DiscoveredContentType> types,
        bool hasInfrastructureTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Aero.Cms.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated JSON serializer context for content type models.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[JsonSourceGenerationOptions(");
        sb.AppendLine("    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,");
        sb.AppendLine("    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("    GenerationMode = JsonSourceGenerationMode.Default | JsonSourceGenerationMode.Metadata)]");

        if (hasInfrastructureTypes)
        {
            // Emit content type infrastructure type registrations only when the
            // actual types exist in the compilation. This avoids compile errors
            // in projects that don't yet reference Aero.Cms.Abstractions.
            sb.AppendLine("[JsonSerializable(typeof(ContentItem))]");
            sb.AppendLine("[JsonSerializable(typeof(ContentTypeDefinition))]");
            sb.AppendLine("[JsonSerializable(typeof(ContentFieldDefinition))]");
            sb.AppendLine("[JsonSerializable(typeof(List<ContentFieldDefinition>))]");
            sb.AppendLine("[JsonSerializable(typeof(Dictionary<string, JsonElement>))]");
            sb.AppendLine("[JsonSerializable(typeof(JsonElement))]");

            // Register each content type's fully-qualified type
            foreach (var type in types)
            {
                sb.AppendLine($"[JsonSerializable(typeof({type.FullyQualifiedName}))]");
            }
        }

        sb.AppendLine();
        sb.AppendLine("public partial class GeneratedContentJsonContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        return sb.Length == 0 ? "Generated" : sb.ToString();
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private readonly struct ContentTypeCandidate
    {
        public readonly string FullyQualifiedName;
        public readonly string Alias;
        public readonly string Name;
        public readonly Location? Location;

        public ContentTypeCandidate(string fqn, string alias, string name, Location? location)
        {
            FullyQualifiedName = fqn;
            Alias = alias;
            Name = name;
            Location = location;
        }
    }

    private readonly struct DiscoveredContentType
    {
        public readonly string FullyQualifiedName;
        public readonly string Alias;
        public readonly string Name;

        public DiscoveredContentType(string fqn, string alias, string name)
        {
            FullyQualifiedName = fqn;
            Alias = alias;
            Name = name;
        }
    }

    private readonly struct CrossAssemblyResult
    {
        public readonly ImmutableArray<DiscoveredContentType> Types;
        public readonly bool HasInfrastructureTypes;

        public CrossAssemblyResult(
            ImmutableArray<DiscoveredContentType> types,
            bool hasInfrastructureTypes)
        {
            Types = types;
            HasInfrastructureTypes = hasInfrastructureTypes;
        }
    }
}
