using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Aero.Cms.SourceGenerators;

/// <summary>
/// Generates embedded marker attributes used by analyzers to identify
/// allowed legacy reflection paths and other sentinel markers.
/// </summary>
[Generator]
public sealed class EmbeddedAttributesGenerator : IIncrementalGenerator
{
        /// <summary>
    /// Initialize method.
    /// </summary>
public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();

            ctx.AddSource("LegacyReflectionDiscoveryAttribute.g.cs", SourceText.From("""
                // <auto-generated />
                #pragma warning disable CS1591
                using System;
                using Microsoft.CodeAnalysis;

                namespace Aero.Cms.Generated;

                /// <summary>
                /// Marks a class or method as an explicitly allowed legacy reflection
                /// discovery path. Analyzers skip diagnostics on code annotated with
                /// this attribute.
                /// </summary>
                [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
                [Embedded]
                internal sealed class LegacyReflectionDiscoveryAttribute : Attribute
                {
                    /// <summary>
                    /// Optional justification for why reflection is needed here.
                    /// </summary>
                    public string? Justification { get; set; }
                }
                """, Encoding.UTF8));
        });
    }
}
