using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Aero.Cms.SourceGenerators;

/// <summary>
/// Host-project incremental source generator.
/// Runs in every project but only emits output when the required types are available.
/// Reads assembly-level attributes from referenced assemblies:
/// <list type="bullet">
///   <item><c>ModuleManifestProviderAttribute</c> — discovers module manifest providers</item>
///   <item><c>WolverineHandlersRegistrationAttribute</c> — discovers Wolverine handler registrations</item>
/// </list>
/// </summary>
[Generator]
public sealed class HostModuleCatalogGenerator : IIncrementalGenerator
{
    private const string ModuleManifestProviderAttributeName = "Aero.Modular.ModuleManifestProviderAttribute";
    private const string WolverineHandlersRegistrationAttributeName = "Aero.Modular.WolverineHandlersRegistrationAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Pipeline: read assembly attributes + check if host compilation has required types
        var hostCatalog = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var moduleProviders = new List<string>();
            var handlerRegistrations = new List<string>();

            // Check if the current compilation has the required types
            var hasAeroModular = false;
            var hasWolverine = false;

            // Check current assembly's own references for Aero.Modular types
            foreach (var referencedAssembly in compilation.SourceModule.ReferencedAssemblySymbols)
            {
                if (referencedAssembly.Name == "Aero.Modular")
                    hasAeroModular = true;

                if (referencedAssembly.Identity.Name is "Wolverine" or "WolverineFx")
                    hasWolverine = true;
            }

            // Only read provider attributes if Aero.Modular is referenced
            if (hasAeroModular)
            {
                foreach (var referencedAssembly in compilation.SourceModule.ReferencedAssemblySymbols)
                {
                    var attributes = referencedAssembly.GetAttributes();

                    foreach (var attr in attributes)
                    {
                        var attrFullName = attr.AttributeClass?.ToDisplayString(
                            SymbolDisplayFormat.FullyQualifiedFormat);

                        if (attrFullName == "global::" + ModuleManifestProviderAttributeName &&
                            attr.ConstructorArguments.Length == 1 &&
                            attr.ConstructorArguments[0].Kind == TypedConstantKind.Type &&
                            attr.ConstructorArguments[0].Value is ITypeSymbol providerType)
                        {
                            var fullName = providerType.ToDisplayString(
                                SymbolDisplayFormat.FullyQualifiedFormat);
                            if (!moduleProviders.Contains(fullName))
                                moduleProviders.Add(fullName);
                        }

                        if (attrFullName == "global::" + WolverineHandlersRegistrationAttributeName &&
                            attr.ConstructorArguments.Length == 1 &&
                            attr.ConstructorArguments[0].Kind == TypedConstantKind.Type &&
                            attr.ConstructorArguments[0].Value is ITypeSymbol handlerRegType)
                        {
                            var fullName = handlerRegType.ToDisplayString(
                                SymbolDisplayFormat.FullyQualifiedFormat);
                            if (!handlerRegistrations.Contains(fullName))
                                handlerRegistrations.Add(fullName);
                        }
                    }
                }
            }

            return new HostCatalogInfo(
                moduleProviders: moduleProviders.ToImmutableArray(),
                handlerRegistrations: handlerRegistrations.ToImmutableArray(),
                hasAeroModular: hasAeroModular,
                hasWolverine: hasWolverine);
        });

        context.RegisterSourceOutput(hostCatalog, static (productionContext, catalog) =>
        {
            if (catalog.HasAeroModular)
            {
                productionContext.AddSource(
                    "GeneratedAeroModuleCatalog.g.cs",
                    SourceText.From(RenderModuleCatalogSource(catalog.ModuleProviders), Encoding.UTF8));

                productionContext.AddSource(
                    "GeneratedHostCatalogMarker.g.cs",
                    SourceText.From(
                        "// <auto-generated />\n" +
                        "namespace Aero.Cms.Web.Generated;\n" +
                        "public static class GeneratedHostCatalogMarker { }\n",
                        Encoding.UTF8));
            }

            if (catalog.HasWolverine)
            {
                productionContext.AddSource(
                    "GeneratedWolverineHandlerCatalog.g.cs",
                    SourceText.From(RenderHandlerCatalogSource(catalog.HandlerRegistrations), Encoding.UTF8));
            }
        });
    }

    private static string RenderModuleCatalogSource(ImmutableArray<string> moduleProviders)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.Linq;");
        source.AppendLine("using Aero.Modular;");
        source.AppendLine();
        source.AppendLine("namespace Aero.Cms.Web.Generated;");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine("/// Source-generated module catalog aggregated from referenced module projects.");
        source.AppendLine("/// </summary>");
        source.AppendLine("public static partial class GeneratedAeroModuleCatalog");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Gets the discovered module manifest provider instances.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    public static IReadOnlyList<IModuleManifestProvider> Providers { get; } =");
        source.AppendLine("    [");

        foreach (var provider in moduleProviders)
        {
            source.AppendLine($"        new {provider}(),");
        }

        source.AppendLine("    ];");
        source.AppendLine();
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Gets the flattened list of module descriptors from all providers.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    public static IReadOnlyList<ModuleDescriptor> Descriptors { get; } =");
        source.AppendLine("        Providers.SelectMany(provider => provider.GetDescriptors()).ToArray();");
        source.AppendLine("}");

        return source.ToString();
    }

    private static string RenderHandlerCatalogSource(ImmutableArray<string> handlerRegistrations)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using Wolverine;");
        source.AppendLine();
        source.AppendLine("namespace Aero.Cms.Web.Generated;");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine("/// Source-generated Wolverine handler catalog aggregated from referenced module projects.");
        source.AppendLine("/// </summary>");
        source.AppendLine("public static partial class GeneratedWolverineHandlerCatalog");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Registers all discovered Wolverine handler types");
        source.AppendLine("    /// after disabling conventional discovery.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    public static void Register(WolverineOptions opts)");
        source.AppendLine("    {");
        source.AppendLine("        opts.Discovery.DisableConventionalDiscovery();");
        source.AppendLine();

        foreach (var registration in handlerRegistrations)
        {
            source.AppendLine($"        {registration}.Register(opts);");
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private readonly struct HostCatalogInfo(
        ImmutableArray<string> moduleProviders,
        ImmutableArray<string> handlerRegistrations,
        bool hasAeroModular,
        bool hasWolverine)
    {
        public ImmutableArray<string> ModuleProviders { get; } = moduleProviders;
        public ImmutableArray<string> HandlerRegistrations { get; } = handlerRegistrations;
        public bool HasAeroModular { get; } = hasAeroModular;
        public bool HasWolverine { get; } = hasWolverine;
    }
}
