using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aero.Cms.SourceGenerators;

/// <summary>
/// Per-module incremental source generator for Wolverine handler discovery.
/// Runs in every project. Finds classes with <c>[WolverineHandler]</c>,
/// and emits a static registration class with explicit <c>IncludeType&lt;T&gt;()</c> calls
/// plus an assembly-level <c>WolverineHandlersRegistrationAttribute</c>.
/// </summary>
/// <remarks>
/// Uses <c>ForAttributeWithMetadataName("Wolverine.Attributes.WolverineHandlerAttribute", ...)</c>
/// as recommended by the Roslyn cookbook for maximum performance.
/// Does NOT scan for <c>IWolverineHandler</c> through <c>AllInterfaces</c>.
/// </remarks>
[Generator]
public sealed class WolverineHandlerGenerator : IIncrementalGenerator
{
    private const string WolverineHandlerAttributeName = "Wolverine.Attributes.WolverineHandlerAttribute";

    /// <summary>
    /// Builds the attributed-handler pipeline and emits a per-assembly registration class.
    /// </summary>
    /// <param name="context">The incremental generator registration context.</param>
    /// <remarks>
    /// No output is emitted when the compilation contains no attributed handler classes. Duplicate
    /// partial declarations are not de-duplicated here; each attribute match becomes an include call.
    /// Generated output disables CS1591 because it is an implementation catalog rather than public API.
    /// </remarks>
public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            WolverineHandlerAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => GetHandlerCandidate(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!.Value)
            .Collect();

        // Combine with compilation to get assembly name at output time
        var combined = handlerCandidates.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (productionContext, tuple) =>
        {
            var (candidates, compilation) = tuple;
            var assemblyName = compilation.AssemblyName ?? "UnknownAssembly";
            var handlerTypes = candidates.ToArray();

            if (handlerTypes.Length == 0)
                return;

            // Emit handler registration source
            productionContext.AddSource(
                "GeneratedWolverineHandlers.g.cs",
                SourceText.From(RenderHandlerSource(assemblyName, handlerTypes), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Converts an attributed class symbol into the names required by generated source.
    /// </summary>
    /// <param name="context">The attribute syntax context for a class candidate.</param>
    /// <returns>The fully qualified type information, or <see langword="null"/> for a non-type target.</returns>
    private static HandlerTypeInfo? GetHandlerCandidate(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol handlerType)
            return null;

        var fullTypeName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new HandlerTypeInfo(
            fullTypeName: fullTypeName,
            typeName: handlerType.Name);
    }

    /// <summary>
    /// Renders the registration type and assembly-level aggregation attribute for one assembly.
    /// </summary>
    /// <param name="assemblyName">The compilation assembly name used to derive namespace and type names.</param>
    /// <param name="handlerTypes">The attributed handler types to include explicitly.</param>
    /// <returns>UTF-8-ready C# source for <c>GeneratedWolverineHandlers.g.cs</c>.</returns>
    private static string RenderHandlerSource(string assemblyName, HandlerTypeInfo[] handlerTypes)
    {
        var safeName = SanitizeIdentifier(assemblyName) + "WolverineHandlers";
        var ns = SanitizeNamespace(assemblyName) + ".Generated";

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#pragma warning disable CS1591");
        source.AppendLine("#nullable enable");
        source.AppendLine("using Wolverine;");
        source.AppendLine();

        // Emit assembly-level attribute for host aggregation
        source.AppendLine($"[assembly: Aero.Modular.WolverineHandlersRegistrationAttribute(typeof({ns}.{safeName}))]");
        source.AppendLine();

        source.AppendLine($"namespace {ns};");
        source.AppendLine();
        source.AppendLine($"public static partial class {safeName}");
        source.AppendLine("{");
        source.AppendLine("    public static void Register(WolverineOptions opts)");
        source.AppendLine("    {");

        foreach (var handler in handlerTypes)
        {
            source.AppendLine($"        opts.Discovery.IncludeType<{handler.FullTypeName}>();");
        }

        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine("#pragma warning restore CS1591");

        return source.ToString();
    }

    /// <summary>
    /// Replaces characters that cannot appear in a generated C# identifier.
    /// </summary>
    /// <param name="value">The source assembly name.</param>
    /// <returns>An alphanumeric/underscore identifier, or <c>Generated</c> when empty.</returns>
    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                builder.Append(ch);
            else
                builder.Append('_');
        }
        return builder.Length == 0 ? "Generated" : builder.ToString();
    }

    /// <summary>
    /// Replaces characters that cannot appear in a generated dotted namespace.
    /// </summary>
    /// <param name="value">The source assembly name.</param>
    /// <returns>A namespace containing only letters, digits, underscores, and periods.</returns>
    private static string SanitizeNamespace(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_' || ch == '.')
                builder.Append(ch);
            else
                builder.Append('_');
        }
        return builder.Length == 0 ? "Generated" : builder.ToString();
    }

    /// <summary>
    /// Carries the symbol names used to render one handler registration.
    /// </summary>
    /// <param name="fullTypeName">The Roslyn fully qualified type name, including <c>global::</c>.</param>
    /// <param name="typeName">The unqualified source type name.</param>
    private readonly struct HandlerTypeInfo(string fullTypeName, string typeName)
    {
        /// <summary>
        /// Gets the fully qualified type name written into generated generic arguments.
        /// </summary>
public string FullTypeName { get; } = fullTypeName;
        /// <summary>
        /// Gets the unqualified handler name retained with the candidate.
        /// </summary>
public string TypeName { get; } = typeName;
    }
}
