using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aero.Cms.SourceGenerators;

/// <summary>
/// Per-module incremental source generator for Wolverine handler discovery.
/// Runs in every project. Finds classes with <c>[WolverineHandler]</c>,
/// and emits a static registration class with explicit <c>IncludeType&lt;T&gt;()</c> calls
/// plus an assembly-level <c>WolverineHandlersRegistrationAttribute</c>.
/// </summary>
/// <remarks>
/// Uses <c>ForAttributeWithMetadataName("Wolverine.Attributes.WolverineHandlerAttribute", ...)</c>
/// as recommended by the Roslyn cookbook for maximum performance.
/// Does NOT scan for <c>IWolverineHandler</c> through <c>AllInterfaces</c>.
/// </remarks>
[Generator]
public sealed class WolverineHandlerGenerator : IIncrementalGenerator
{
    private const string WolverineHandlerAttributeName = "Wolverine.Attributes.WolverineHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            WolverineHandlerAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => GetHandlerCandidate(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!.Value)
            .Collect();

        // Combine with compilation to get assembly name at output time
        var combined = handlerCandidates.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (productionContext, tuple) =>
        {
            var (candidates, compilation) = tuple;
            var assemblyName = compilation.AssemblyName ?? "UnknownAssembly";
            var handlerTypes = candidates.ToArray();

            if (handlerTypes.Length == 0)
                return;

            // Emit handler registration source
            productionContext.AddSource(
                "GeneratedWolverineHandlers.g.cs",
                SourceText.From(RenderHandlerSource(assemblyName, handlerTypes), Encoding.UTF8));
        });
    }

    private static HandlerTypeInfo? GetHandlerCandidate(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol handlerType)
            return null;

        var fullTypeName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new HandlerTypeInfo(
            fullTypeName: fullTypeName,
            typeName: handlerType.Name);
    }

    private static string RenderHandlerSource(string assemblyName, HandlerTypeInfo[] handlerTypes)
    {
        var safeName = SanitizeIdentifier(assemblyName) + "WolverineHandlers";
        var ns = SanitizeNamespace(assemblyName) + ".Generated";

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using Wolverine;");
        source.AppendLine();

        // Emit assembly-level attribute for host aggregation
        source.AppendLine($"[assembly: Aero.Modular.WolverineHandlersRegistrationAttribute(typeof({ns}.{safeName}))]");
        source.AppendLine();

        source.AppendLine($"namespace {ns};");
        source.AppendLine();
        source.AppendLine($"public static partial class {safeName}");
        source.AppendLine("{");
        source.AppendLine("    public static void Register(WolverineOptions opts)");
        source.AppendLine("    {");

        foreach (var handler in handlerTypes)
        {
            source.AppendLine($"        opts.Discovery.IncludeType<{handler.FullTypeName}>();");
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                builder.Append(ch);
            else
                builder.Append('_');
        }
        return builder.Length == 0 ? "Generated" : builder.ToString();
    }

    private static string SanitizeNamespace(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_' || ch == '.')
                builder.Append(ch);
            else
                builder.Append('_');
        }
        return builder.Length == 0 ? "Generated" : builder.ToString();
    }

    private readonly struct HandlerTypeInfo(string fullTypeName, string typeName)
    {
        public string FullTypeName { get; } = fullTypeName;
        public string TypeName { get; } = typeName;
    }
}
