<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aero\src\Aero.Core\Aero.Core.csproj" />
    <ProjectReference Include="..\..\AeroDB\src\AeroDB.Sable\AeroDB.Sable.csproj" />
    <ProjectReference Include="..\Aero.Cms.Abstractions\Aero.Cms.Abstractions.csproj" />
  </ItemGroup>

</Project>
