using System.Text.Json;
using System.Text.Json.Serialization;
using Aero.Cms.Abstractions.Enums;
using Aero.Cms.Abstractions.Interfaces;
using Aero.Cms.Abstractions.Models;
using Aero.Cms.Html;
using Aero.Core.Data;
using AeroDB.Sable;

namespace Aero.Cms.Core.Entities;


/// <summary>
/// Represents a class for PageDocument.
/// </summary>
public sealed class PageDocument : SableDocument, IAuditable, ISiteOwned, ISoftDeleted, IAuditableEntity
{
        /// <summary>
    /// Gets or sets the Site Id.
    /// </summary>
public long SiteId { get; set; }
        /// <summary>
    /// Gets or sets the Translation Group Id.
    /// </summary>
public long? TranslationGroupId { get; set; }
        /// <summary>
    /// Gets or sets the Source Page Id.
    /// </summary>
public long? SourcePageId { get; set; }
        /// <summary>
    /// Gets or sets the Culture.
    /// </summary>
public string Culture { get; set; } = SitesModel.DefaultCultureName;
        /// <summary>
    /// Gets or sets the Kind.
    /// </summary>
public PageKind Kind { get; set; } = PageKind.Standard;
        /// <summary>
    /// Gets or sets the Slug.
    /// </summary>
public string Slug { get; set; } = string.Empty;
        /// <summary>
    /// Gets or sets the Title.
    /// </summary>
public string Title { get; set; } = string.Empty;
        /// <summary>
    /// Gets or sets the Summary.
    /// </summary>
public string? Summary { get; set; }
        /// <summary>
    /// Gets or sets the Seo Title.
    /// </summary>
public string? SeoTitle { get; set; }
        /// <summary>
    /// Gets or sets the Seo Description.
    /// </summary>
public string? SeoDescription { get; set; }

    // ── Hierarchy ───────────────────────────────────────────────────────

    /// <summary>
    /// Parent page ID. <c>null</c> for root-level pages.
    /// </summary>
    public long? ParentId { get; set; }

    /// <summary>
    /// Full materialized path (e.g. "/sports/basketball/nba").
    /// </summary>
    public string Path { get; set; } = "/";

    /// <summary>
    /// Distance from root. 0 = root, 1 = direct child, etc.
    /// </summary>
    public int Depth { get; set; }

    /// <summary>
    /// Display order among siblings. Lower = first. Insertions require renumbering.
    /// </summary>
    public int Order { get; set; }

    /// <summary>
    /// When <c>true</c>, this page and all descendants are hidden from navigation menus.
    /// </summary>
    public bool IsHidden { get; set; }

    // ── Layout ───────────────────────────────────────────────────────────

    /// <summary>
    /// Gets or sets the editable HTML fragment owned by this page aggregate.
    /// </summary>
    public HtmlPageContent DraftContent { get; set; } = new();

    /// <summary>
    /// Gets or sets the immutable-at-rest HTML snapshot currently available to public rendering.
    /// </summary>
    public HtmlPageContent? PublishedContent { get; set; }

    /// <summary>
    /// Replaces the editable draft with an independent validated snapshot.
    /// Validation is performed by the Pages application boundary before this mutation.
    /// </summary>
    public void ReplaceDraftContent(HtmlPageContent content, DateTimeOffset modifiedOn)
    {
        ArgumentNullException.ThrowIfNull(content);

        DraftContent = HtmlTreeOperations.ClonePreservingNodeIds(content);
        ContentRevision = checked(ContentRevision + 1);
        ModifiedOn = modifiedOn;
    }

    /// <summary>
    /// Publishes an independent snapshot of the current validated draft.
    /// </summary>
    public void PublishDraftContent(DateTimeOffset publishedOn)
    {
        PublishedContent = HtmlTreeOperations.ClonePreservingNodeIds(DraftContent);
        PublicationState = ContentPublicationState.Published;
        PublishedOn = publishedOn;
        PublishedVersion = checked(PublishedVersion + 1);
        ModifiedOn = publishedOn;
    }

    /// <summary>
    /// Removes public availability while preserving the last published snapshot.
    /// </summary>
    public void UnpublishContent(DateTimeOffset modifiedOn)
    {
        PublicationState = ContentPublicationState.Draft;
        PublishedOn = null;
        ModifiedOn = modifiedOn;
    }

    /// <summary>
    /// Latest draft content revision generated by the composition pipeline.
    /// This is distinct from AeroDB optimistic concurrency metadata.
    /// </summary>
    public long ContentRevision { get; set; }

        /// <summary>
    /// Gets or sets the Publication State.
    /// </summary>
public ContentPublicationState PublicationState { get; set; } = ContentPublicationState.Draft;
        /// <summary>
    /// Gets or sets the Published On.
    /// </summary>
public DateTimeOffset? PublishedOn { get; set; } = null;

    /// <summary>
    /// Monotonic counter incremented on every publish.
    /// </summary>
    public long PublishedVersion { get; set; }

        /// <summary>
    /// Gets or sets the Is Publicly Visible.
    /// </summary>
    [JsonIgnore]
    public bool IsPubliclyVisible =>
        PublicationState == ContentPublicationState.Published && !Deleted;

    /// <summary>
    /// Gets or sets whether this page should be displayed in the main navigation menu.
    /// </summary>
    public bool ShowInNavMenu { get; set; } = true;

    /// <summary>
    /// Gets or sets whether the global header navigation should be shown when viewing this page.
    /// </summary>
    public bool ShowHeaderNavigation { get; set; } = true;

    /// <summary>
    /// Gets or sets an optional image URL to be used as a background for the page header/hero section.
    /// </summary>
    public string? HeaderImageUrl { get; set; }

    /// <summary>
    ///  Flag to hide the header on the page
    /// </summary>
    public bool HideHeader { get; set; } = false;
    /// <summary>
    ///  Flag to hide the footer on the page
    /// </summary>
    public bool HideFooter { get; set; } = false;

    /// <summary>
    /// Gets or sets whether the chat agent widget should be shown on this page.
    /// </summary>
    public bool ShowChatAgent { get; set; } = true;

    // ── Soft Delete ──────────────────────────────────────────────────────

    /// <summary>
    /// <c>true</c> when the page has been soft-deleted via AeroDB.
    /// Managed automatically by AeroDB's <c>ISoftDeleted</c> policy.
    /// </summary>
    public bool Deleted { get; set; }

    /// <summary>
    /// Timestamp of soft deletion. Managed automatically by AeroDB.
    /// </summary>
    public DateTimeOffset? DeletedAt { get; set; }

    // IAuditable
    public DateTimeOffset CreatedOn { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? ModifiedOn { get; set; }
    public string? CreatedBy { get; set; }
    public string? ModifiedBy { get; set; }

    /// <summary>
    /// Maps this document to a <see cref="PageViewModel"/> for Wolverine
    /// message bus publishing.  Avoids exposing the internal PageDocument
    /// type to downstream consumers.
    /// </summary>
    public PageViewModel ToViewModel() => new()
    {
        Id = Id,
        Title = Title,
        Slug = Slug,
        Kind = Kind,
        Summary = Summary,
        SeoTitle = SeoTitle,
        SeoDescription = SeoDescription,
        PublishedOn = PublishedOn,
        IsPublished = PublicationState == ContentPublicationState.Published,
        PublicationState = PublicationState,
        SiteId = SiteId,
        Culture = Culture,
        TranslationGroupId = TranslationGroupId,
        ParentId = ParentId,
        Path = Path,
        Depth = Depth,
        Order = Order,
        IsHidden = IsHidden,
        ShowInNavMenu = ShowInNavMenu,
        ShowHeaderNavigation = ShowHeaderNavigation,
        HideFooter = HideFooter,
        ShowChatAgent = ShowChatAgent,
        ContentRevision = ContentRevision,
        DraftContentJson = JsonSerializer.Serialize(DraftContent, HtmlJsonContext.Default.HtmlPageContent),
        PublishedContentJson = PublishedContent is null
            ? null
            : JsonSerializer.Serialize(PublishedContent, HtmlJsonContext.Default.HtmlPageContent)
    };
}
