using Aero.Validators.Extensions;
using FluentValidation;

namespace Aero.Cms.Modules.Banner;

/// <summary>
/// Represents a class for BannerValidator.
/// </summary>
public class BannerValidator : AbstractValidator<BannerModel>
{
        /// <summary>
    /// Initializes a new instance of the <see cref="BannerValidator"/> class.
    /// </summary>
public BannerValidator()
    {
        RuleFor(x => x.Id)
            .GreaterThan(0)
            .WithMessage("the id must be greator than 0 and should be generated by the snowflake algorithm");
        RuleFor(x => x.Name)
            .NotNullOrEmpty()
            .WithMessage("name is required");
        RuleFor(x => x.StartDate)
            .NotNullOrEmpty()
            .WithMessage("start date is required for banners");
        RuleFor(x => x.EndDate)
            .NotNullOrEmpty()
            .WithMessage("end date is required for banners");
    }
}