using Aero.Cms.Modules.Commerce.Catalog.Models;
using FluentValidation;

namespace Aero.Cms.Modules.Commerce.Catalog.Validation;

public sealed class ProductValidator : AbstractValidator<ProductDocument>
{
    public ProductValidator()
    {
        RuleFor(x => x.Id)
            .GreaterThan(0)
            .WithMessage("Id must be greater than 0 and should be generated by the snowflake algorithm");

        RuleFor(x => x.Name)
            .NotEmpty()
            .MaximumLength(500)
            .WithMessage("Product name is required and must be at most 500 characters");

        RuleFor(x => x.Slug)
            .NotEmpty()
            .WithMessage("Slug is required");

        RuleFor(x => x.Price)
            .GreaterThanOrEqualTo(0)
            .WithMessage("Price must be greater than or equal to 0");

        RuleFor(x => x.StockQuantity)
            .GreaterThanOrEqualTo(0)
            .WithMessage("Stock quantity must be greater than or equal to 0");
    }
}
