export default class ArrayUtility {
    private static compareDateType;
    private static invokeSortBy;
    static all<T>(items: readonly T[], predicate: (item: T, index: number) => boolean): boolean;
    static any<T>(items: readonly T[], predicate?: (item: T, index: number) => boolean): boolean;
    static where<T>(items: readonly T[], predicate: (item: T, index: number) => boolean): T[];
    static whereAsync<T>(items: readonly T[], predicate: (item: T) => Promise<boolean>): Promise<T[]>;
    static select<T, TResult>(source: readonly T[], selector: (item: T, index: number) => TResult): TResult[];
    static selectMany<TIn, TOut>(items: readonly TIn[], collectionSelector: (item: TIn) => TOut[]): TOut[];
    static chunk<T>(items: readonly T[], size: number): T[][];
    static split<T>(items: readonly T[], count: number): T[][];
    static take<T>(items: readonly T[], count: number): T[];
    static takeLast<T>(items: readonly T[], count: number): T[];
    static takeWhile<T>(items: readonly T[], predicate: (item: T, index: number) => boolean): T[];
    static toDictionary<T, TKey = T, TElement = T>(items: readonly T[], keySelector?: ((item: T, index: number) => TKey) | null, elementSelector?: ((item: T, index: number) => TElement) | null): Map<TKey, TElement[]>;
    static toHashSet<T, TKey = T>(items: readonly T[], keySelector?: ((item: T, index: number) => TKey) | null): Set<TKey>;
    static single<T>(items: readonly T[], predicate?: ((item: T) => boolean) | null, defaultValue?: T | null): T;
    static singleOrDefault<T>(items: readonly T[], predicate?: ((item: T) => boolean) | null, defaultValue?: T | null): T | null;
    static skip<T>(items: readonly T[], count: number): T[];
    static skipLast<T>(items: readonly T[], count: number): T[];
    static skipWhile<T>(items: readonly T[], predicate: (item: T, index: number) => boolean): T[];
    static first<T>(items: readonly T[], predicate?: ((item: T) => boolean) | null, defaultValue?: T | null): T;
    static firstOrDefault<T>(items: readonly T[], predicate?: ((item: T) => boolean) | null, defaultValue?: T | null): T | null;
    static last<T>(items: readonly T[], predicate?: ((item: T) => boolean) | null, defaultValue?: T | null): T;
    static lastOrDefault<T>(items: readonly T[], predicate?: ((item: T) => boolean) | null, defaultValue?: T | null): T | null;
    static forEachAsync<T>(items: readonly T[], predicate: (item: T) => Promise<void>): Promise<void>;
    static except<T>(items: readonly T[], except: readonly T[], comparer?: ((x: T, y: T) => boolean) | null): T[];
    static groupBy<T, TKey = T, TElement = TKey>(items: readonly T[], keySelector?: ((item: T, index: number) => TKey) | null, elementSelector?: ((item: T, index: number) => TElement) | null): TElement[][];
    static remove<T>(items: T[], item: T | T[] | ((item: T, index: number) => boolean)): void;
    static removeAt<T>(items: T[], index: number): void;
    static max<T>(items: readonly T[], keySelector?: ((item: T) => number) | null): T;
    static maxValue<T>(items: readonly T[], keySelector: (item: T) => number): number;
    static min<T, TValue = number | Date>(items: readonly T[], keySelector?: ((item: T) => TValue) | null): T;
    static minValue<T, TValue = number | Date>(items: readonly T[], predicate: (item: T) => TValue): TValue;
    static sum<T>(items: readonly T[] | null | undefined, selector?: ((item: T) => number | null | undefined) | null): number;
    static count<T>(items: readonly T[] | null | undefined, predicate?: ((item: T, index: number) => boolean) | null): number;
    static contains<T>(items: readonly T[], value: T): boolean;
    static distinct<T>(items: readonly T[], predicate?: ((item: T) => any) | null): T[];
    static repeat<T>(element: T, count: number): T[];
    static insert<T>(items: T[], item: T | readonly T[], index?: number | null): void;
    static average<T>(items: readonly T[], selector?: ((item: T) => number | null | undefined) | null): number;
    static sortBy<T, TKey1, TKey2, TKey3, TKey4, TKey5, TKey6>(source: T[], keySelector1?: ((item: T) => TKey1) | null, keySelector2?: ((item: T) => TKey2) | null, keySelector3?: ((item: T) => TKey3) | null, keySelector4?: ((item: T) => TKey4) | null, keySelector5?: ((item: T) => TKey5) | null, keySelector6?: ((item: T) => TKey6) | null): void;
    static sortByDescending<T, TKey1, TKey2, TKey3, TKey4, TKey5, TKey6>(source: T[], keySelector1?: ((item: T) => TKey1) | null, keySelector2?: ((item: T) => TKey2) | null, keySelector3?: ((item: T) => TKey3) | null, keySelector4?: ((item: T) => TKey4) | null, keySelector5?: ((item: T) => TKey5) | null, keySelector6?: ((item: T) => TKey6) | null): void;
}
