using Aero.Core.Data;
using AeroDB.Sable;
using System.Text.Json.Serialization;

namespace Aero.Cms.Modules.Commerce.Subscriptions;

/// <summary>Durable lifecycle state for a provider-owned subscription.</summary>
public enum SubscriptionState
{
    PendingProviderConfirmation = 0,
    Active = 10,
    PastDue = 20,
    Cancelled = 30,
    Expired = 40,
    ManualReview = 100
}

/// <summary>Durable lifecycle state for an individual provider billing cycle.</summary>
public enum SubscriptionCycleState
{
    Open = 0,
    Paid = 10,
    Failed = 20,
    Cancelled = 30,
    ManualReview = 100
}

/// <summary>Processing state for a verified provider subscription webhook receipt.</summary>
public enum SubscriptionWebhookReceiptState
{
    Received = 0,
    Applied = 10,
    Ignored = 20,
    ManualReview = 100
}

/// <summary>
/// Immutable commercial snapshot for one line in a provider-owned subscription.
/// Provider offer identifiers are references only and never contain credentials.
/// </summary>
public sealed class SubscriptionLineSnapshot
{
    public long ProductId { get; set; }
    public long ListingId { get; set; }
    public string ProductName { get; set; } = string.Empty;
    public string ListingName { get; set; } = string.Empty;
    public string Sku { get; set; } = string.Empty;
    public int Quantity { get; set; }
    public decimal UnitAmount { get; set; }
    public string ProviderOfferReference { get; set; } = string.Empty;
    [JsonIgnore]
    public decimal TotalAmount => UnitAmount * Quantity;
}

/// <summary>
/// Tenant-, site-, and member-scoped snapshot of a recurring purchase managed by Stripe or PayPal.
/// Recurring collection, scheduling, and off-session charging remain exclusively provider-owned.
/// </summary>
public sealed class SubscriptionDocument : SableDocument, IAuditable, IVersioned
{
    public long TenantId { get; set; }
    public long SiteId { get; set; }
    public long ExternalMemberId { get; set; }
    /// <summary>Recurring Commerce order that owns this initial provider checkout.</summary>
    public long OrderId { get; set; }
    public string Provider { get; set; } = string.Empty;
    public string ProviderAccountKey { get; set; } = string.Empty;
    /// <summary>Stable provider idempotency key generated by Commerce before external I/O.</summary>
    public string ProviderOperationKey { get; set; } = string.Empty;

    /// <summary>
    /// Required stable reference returned by initial provider checkout creation, such as a
    /// Stripe Checkout Session or PayPal subscription approval resource.
    /// </summary>
    public string? ProviderCheckoutReference { get; set; }

    /// <summary>Provider subscription reference populated after provider confirmation.</summary>
    public string? ProviderSubscriptionReference { get; set; }

    /// <summary>Provider customer/subscriber reference populated when the provider supplies one.</summary>
    public string? ProviderCustomerReference { get; set; }

    public List<SubscriptionLineSnapshot> Lines { get; set; } = [];
    public string Currency { get; set; } = "USD";
    public int IntervalDays { get; set; }
    public SubscriptionState State { get; set; } = SubscriptionState.PendingProviderConfirmation;

    /// <summary>Last verified provider event applied after monotonic transition checks.</summary>
    public string? LastAppliedProviderEventId { get; set; }
    public DateTimeOffset? LastAppliedProviderOccurredOn { get; set; }

    public DateTimeOffset? CurrentPeriodStartsOn { get; set; }
    public DateTimeOffset? CurrentPeriodEndsOn { get; set; }
    public bool CancelAtPeriodEnd { get; set; }
    public bool RequiresManualReview { get; set; }
    public string? ManualReviewReason { get; set; }
    public DateTimeOffset? ManualReviewRequestedOn { get; set; }
    public DateTimeOffset CreatedOn { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? ModifiedOn { get; set; }
    public string? CreatedBy { get; set; }
    public string? ModifiedBy { get; set; }
    public long Version { get; set; }

    [JsonIgnore]
    public decimal TotalAmount => Lines.Sum(line => line.TotalAmount);
}

/// <summary>Immutable commercial snapshot and provider state for one subscription billing cycle.</summary>
public sealed class SubscriptionCycleDocument : SableDocument, IAuditable, IVersioned
{
    public long TenantId { get; set; }
    public long SiteId { get; set; }
    public long ExternalMemberId { get; set; }
    public long SubscriptionId { get; set; }
    public int CycleNumber { get; set; }
    public string Provider { get; set; } = string.Empty;
    public string ProviderAccountKey { get; set; } = string.Empty;

    /// <summary>Provider invoice, sale, or capture reference that uniquely identifies this cycle.</summary>
    public string ProviderCycleReference { get; set; } = string.Empty;

    /// <summary>Provider payment reference for this cycle; never a payment secret.</summary>
    public string? ProviderPaymentReference { get; set; }

    /// <summary>Reference to a one-time Commerce payment attempt when the initial cycle has one.</summary>
    public long? PaymentAttemptId { get; set; }

    public List<SubscriptionLineSnapshot> Lines { get; set; } = [];
    public decimal AmountSnapshot { get; set; }
    public string Currency { get; set; } = "USD";
    public DateTimeOffset PeriodStartsOn { get; set; }
    public DateTimeOffset PeriodEndsOn { get; set; }
    public SubscriptionCycleState State { get; set; } = SubscriptionCycleState.Open;

    /// <summary>Last verified provider event applied after monotonic transition checks.</summary>
    public string? LastAppliedProviderEventId { get; set; }
    public DateTimeOffset? LastAppliedProviderOccurredOn { get; set; }

    public bool RequiresManualReview { get; set; }
    public string? ManualReviewReason { get; set; }
    public DateTimeOffset? ManualReviewRequestedOn { get; set; }
    public DateTimeOffset CreatedOn { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? ModifiedOn { get; set; }
    public string? CreatedBy { get; set; }
    public string? ModifiedBy { get; set; }
    public long Version { get; set; }
}

/// <summary>
/// Deduplicated verified subscription webhook receipt. Raw payloads, signatures, secrets,
/// and browser-continuation URLs are intentionally not persisted.
/// </summary>
public sealed class SubscriptionWebhookReceiptDocument : SableDocument, IVersioned
{
    public long TenantId { get; set; }
    public long SiteId { get; set; }
    public long? ExternalMemberId { get; set; }
    public long? SubscriptionId { get; set; }
    public long? SubscriptionCycleId { get; set; }
    public string Provider { get; set; } = string.Empty;
    public string ProviderAccountKey { get; set; } = string.Empty;
    public string ProviderEventId { get; set; } = string.Empty;
    public DateTimeOffset ProviderOccurredOn { get; set; }
    public string? ProviderSubscriptionReference { get; set; }
    public string? ProviderCycleReference { get; set; }
    public string? ProviderPaymentReference { get; set; }
    public DateTimeOffset ReceivedOn { get; set; } = DateTimeOffset.UtcNow;
    public SubscriptionWebhookReceiptState State { get; set; } = SubscriptionWebhookReceiptState.Received;
    public string? ManualReviewReason { get; set; }
    public long Version { get; set; }
}
