<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnableTestingPlatform>true</EnableTestingPlatform>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="TUnit" Version="1.58.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Aero.Cms.Abstractions\Aero.Cms.Abstractions.csproj" />
  </ItemGroup>

</Project>
