<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>Aero.Cms.Modules.Commerce.Client</RootNamespace>
    <AeroCmsSkipWebCoreReference>true</AeroCmsSkipWebCoreReference>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aero.Cms.Shared\Aero.Cms.Shared.csproj"
                      AdditionalProperties="AeroCmsBrowserClient=$(AeroCmsBrowserClient)" />
  </ItemGroup>

</Project>
