<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aero.Cms.Abstractions\Aero.Cms.Abstractions.csproj" />
    <ProjectReference Include="..\Aero.Cms.Core\Aero.Cms.Core.csproj" />
    <ProjectReference Include="..\..\Aero\src\Aero.Core\Aero.Core.csproj" />
    <ProjectReference Include="..\..\Aero\src\Aero.Modular\Aero.Modular.csproj" />
  </ItemGroup>
</Project>
