<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WorkOS.net" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\WorkOS\Pages\" />
  </ItemGroup>



</Project>
