<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Aero\src\Aero.Caching\Aero.Caching.csproj" />
    <ProjectReference Include="..\Aero.Cms.Abstractions\Aero.Cms.Abstractions.csproj" />
    <ProjectReference Include="..\Aero.Cms.Core\Aero.Cms.Core.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Posts\Aero.Cms.Modules.Posts.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Cache\Aero.Cms.Modules.Cache.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Docs\Aero.Cms.Modules.Docs.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Pages\Aero.Cms.Modules.Pages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AeroDB\src\AeroDB\AeroDB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="ZiggyCreatures.FusionCache" />
  </ItemGroup>

</Project>
