<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
	  <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
	  <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Api\v1\BlogApiV2.cs" />
    <Compile Remove="Api\v1\PagesApiV2.cs" />
    <Compile Remove="Areas\Api\v1\PublishApi.cs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aero.Cms.Abstractions\Aero.Cms.Abstractions.csproj" />
    <ProjectReference Include="..\Aero.Cms.Banners\Aero.Cms.Banners.csproj" />
    <ProjectReference Include="..\Aero.Cms.Core\Aero.Cms.Core.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Blog\Aero.Cms.Modules.Blog.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Aliases\Aero.Cms.Modules.Aliases.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Media\Aero.Cms.Modules.Media.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Docs\Aero.Cms.Modules.Docs.csproj" />
    <ProjectReference Include="..\Aero.Cms.Modules.Pages\Aero.Cms.Modules.Pages.csproj" />
    <ProjectReference Include="..\Aero.Cms.Web.Core\Aero.Cms.Web.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Areas\Api\v1\BlogApiV2.cs" />
    <None Include="Areas\Api\v1\PagesApiV2.cs" />
    <Compile Remove="Areas\Api\v1\BlogApiV2.cs" />
    <None Include="Areas\Api\v1\BlogApiV2.cs" />
    <Compile Remove="Areas\Api\v1\PagesApiV2.cs" />
    <None Include="Areas\Api\v1\PagesApiV2.cs" />
    <None Include="Areas\Api\v1\PublishApi.cs" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Areas\MyFeature\Pages\Page1.cshtml" />
  </ItemGroup>



</Project>
